<?php

declare(strict_types=1);

/*
 * This file is part of JoliCode's Slack PHP API project.
 *
 * (c) JoliCode <coucou@jolicode.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace JoliCode\Slack;

use Http\Client\Common\Exception\ClientErrorException;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\HeaderAppendPlugin;
use Http\Client\Common\Plugin\RetryPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Exception\HttpException;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use JoliCode\Slack\HttpPlugin\AddSlackPathAndHostPlugin;
use JoliCode\Slack\HttpPlugin\SlackErrorPlugin;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Client\ClientInterface;

class ClientFactory
{
    public static function create(string $token, ?ClientInterface $httpClient = null): Client
    {
        // Find a default HTTP client if none provided
        if (null === $httpClient) {
            $httpClient = Psr18ClientDiscovery::find();
        }

        // Decorates the HTTP client with some plugins
        $uri = Psr17FactoryDiscovery::findUriFactory()->createUri('https://slack.com/api');
        $pluginClient = new PluginClient($httpClient, [
            new SlackErrorPlugin(),
            new AddSlackPathAndHostPlugin($uri),
            new HeaderAppendPlugin([
                'Authorization' => 'Bearer ' . $token,
            ]),
            new RetryPlugin([
                'retries' => 3,
                'exception_decider' => function (RequestInterface $request, ClientExceptionInterface $e) {
                    // retry only server errors and rate limits
                    return !$e instanceof HttpException || ($e->getCode() === 429 || ($e->getCode() >= 500 && $e->getCode() < 600));
                },
                'exception_delay' => function (RequestInterface $request, ClientExceptionInterface $e, int $retries): int {
                    if ($e instanceof ClientErrorException) {
                        $response = $e->getResponse();
                        if ($response->hasHeader('Retry-After')) {
                            $retryAfter = (int) $response->getHeaderLine('retry-after');
                            return $retryAfter * 1000000;
                        }
                    }

                    return RetryPlugin::defaultExceptionDelay($request, $e, $retries);
                },
            ]),
            new ErrorPlugin(),                            
        ]);

        // Instantiate our client extending the one generated by Jane
        return Client::create($pluginClient);
    }
}
